### PR TITLE
Schedule DHT re-announce after announce completes

### PR DESCRIPTION
**Pull request by feross**
Supersedes this PR: https://github.com/feross/torrent-discovery/pull/16

cc @mafintosh @oleiba

### CODE REVIEW

**Comment by feross** [comment]
Does this look good to you @oleiba?

**Comment by oleiba** [comment]
Yup. Scheduling a re-announce once previous has completed ensures seeds will not stop being available, and this solution still ensures no simultaneous announces.
I was wondering about how to make DHT announces to complete faster than tens of minutes when seeding hundreds of files (this issue makes initial seeds to be available only once in a few announce cycles of the downloader client) - but I suppose that's a separate issue. 
Thanks!

**Comment by feross** [comment]
@oleiba Yes, that's a separate issue. Consider opening that as a new issue on `bittorrent-dht`.

**Comment by feross** [comment]
Released as 5.3.3.

**Pull request merged**
